### PR TITLE
Separate the CFE stubs from UT test cases

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Fix issue #415

Build the CFE UT stub library separately from the test cases.
This moves the stub files into a separate ut-stubs directory,
and the library is now called "ut_cfe_core_stubs"

Note: Minor cleanup also done as part of moving.  Two stub
files were in the source tree but not being built or used
by any framework test config.  These were:
  ut_arinc653_stubs.c
  ut_configdata_stubs.c

These are now removed.  Also cleaned up some old macros/ifdefs
that were never enabled or used in the current tests.

**Testing performed**
Build CFE using default configuration with ENABLE_UNIT_TEST=TRUE.  Confirm CFE core executes normally.  Confirm all CFE unit tests build and run as normal.

**Expected behavior changes**
No impact to behavior.  CFE FSW code is unchanged, this only affects UT build/link procedure.

**System(s) tested on:**
Ubuntu 18.04 LTS 64-bit

**Contributor Info**
Joseph Hickey, Vantage Systems, Inc.

**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted

### CODE REVIEW

**Comment by jphickey** [comment]
Also note: I noticed that the stub for the `CFE_TBL_GetInfo` function was missing, so this also adds it.

**Comment by skliper** [comment]
fsw to me means "flight software".  Could the stubs and unit tests be moved out of the flight software directory as part of this change?  I'd expect the fsw directory to only contain flight code.

**Comment by jphickey** [comment]
> fsw to me means "flight software". Could the stubs and unit tests be moved out of the flight software directory as part of this change? I'd expect the fsw directory to only contain flight code.

Yes, I concur that it doesn't make sense for this to be under "fsw".

But the difficulty for CFE stuff is that the "cfe-core" dir is considered the top level for all source code (i.e. this is where ${cfe-core_MISSION_DIR} points to) which is unfortunately a subdir of "fsw".

Perhaps the easiest solution would be swapping the "fsw" and "cfe-core" subdirs, so the path to the FSW would become:
`cfe-core/fsw/src/<module>`
rather than:
`fsw/cfe-core/src/<module`
as it is today.  That way the unit test stubs can reside at:
`cfe-core/ut-stubs`

Such a directory change seems like it should be a separate ticket/pull request though.

**Comment by skliper** [comment]
> Such a directory change seems like it should be a separate ticket/pull request though.

I concur, a bigger change as suggested is worth a separate ticket.

**Comment by skliper** [comment]
CCB 20191218 - Reviewed and approved for IC

**Pull request merged**
