### PR TITLE
Fix #657, Add UT_Stub_RegisterContext to CFE_EVS_SendEvent and CFE_ES_WriteToSysLog

### LINKED ISSUE #657: Missing registering contexts in stub functions
I’ll work this issue

The issue causes seg faults cause by not registering contexts. I resolved this by adding the missing registrations.
 

cfe/fsw/cfe-core/ut-stubs/ut_evs_stubs.c:
int32 CFE_EVS_SendEvent(uint16 EventID,
                        uint16 EventType,
                        const char *Spec,
                        ...)
{
    int32 status;
    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), &EventID);
    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), &EventType);  <----- missing
    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), Spec);              <----- missing
..
}
 
cfe/fsw/cfe-core/ut-stubs/ ut_es_stubs.c:
int32 CFE_ES_WriteToSysLog(const char *pSpecString, ...)
{
    int32   status;
    UT_Stub_RegisterContext(UT_KEY(CFE_ES_WriteToSysLog), pSpecString);  <----- missing
 ...}

Expected behavior
Return register buffer size=3 when using CFE_EVS_SendEvent and buffer size =1 when using CFE_ES_WriteToSysLog.

System observed on:

Hardware
OS: Centos 7
Versions:cFE 6.7.12.0, OSAL 5.0.11.0, PSP 1.4.8.0, chksm 9194

Reporter Info
Jose Tovias CACI/LZT Technology

### PR DESCRIPTION
**Pull request by jtovias**
Add missing UT_Stub_RegisterContext to CFE_EVS_SendEvent and CFE_ES_WriteToSysLog.
This will create the correct register buffer size.

**Describe the contribution**
Add missing UT_Stub_RegisterContext to CFE_EVS_SendEvent and CFE_ES_WriteToSysLog.
This will create the correct register buffer size.
- Fixes #657

**Testing performed**
Steps taken to test the contribution:

travis CI passed:    https://travis-ci.com/github/jtovias/cFS/builds/164052416

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - Behavior Change:
      - using ut stubs CFE_EVS_SendEvent and CFE_ES_WriteToSysLog, the register buffer will have the correct size
     - access to register buffer element will exist

**System(s) tested on**
 - Hardware:PC and UT700
 - OS: Centos 7 and VxWorks6.9
 - Versions: cFE 6.7.12.0, OSAL 5.0.11.0, PSP 1.4.8.0, chksm 9194

**Additional context**
None.

**Third party code**
None.

**Contributor Info - All information REQUIRED for consideration of pull request**
Jose Tovias/ CACI-LZT Technology/JSC 
  - JSC B32:R205/jose.a.tovias@nasa.gov/281-244-8154/ NASA Contract # NNJ14HA04B/Task Order 119: Exploration Extravehicular Mobility Unit (xEMU) Software Development and Engineering Support
  - HAND SIGNED Company CLA has been emailed to GSFC-SoftwareRelease@mail.nasa.gov.
copy sent:  [GSC_18128_Corp_CLA_form_1219_JoseTovias_for_cFE6.7.pdf](https://github.com/nasa/cFE/files/4593753/GSC_18128_Corp_CLA_form_1219_JoseTovias_for_cFE6.7.pdf)

### CODE REVIEW

**Comment by astrogeco** [comment]
CCB 20200506 - APPROVED

**Comment by skliper** [comment]
@jtovias - could you fill out the remainder of the sections in the pull request template, and submit the [Company CLA](../docs/GSC_18128_Corp_CLA_form_1219.pdf)

**Comment by skliper** [comment]
Amend commit message - 
```
Fix #657, Add unit test stub register context to cFE stubs

UT_Stub_RegisterContext added to CFE_EVS_SendEvent and CFE_ES_WriteToSysLog
```

**Comment by jtovias** [comment]
@skliper, if working for a NASA contract do I still need to submit a Company CLA?

**Comment by skliper** [comment]
> @skliper, if working for a NASA contract do I still need to submit a Company CLA?

Yes, our office of patent counsel requires us to have a CLA for any contract other than our one local contract they have explicitly approved.

**Comment by skliper** [comment]
@jtovias Any status update/progress on the CLA?

**Comment by jtovias** [comment]
@skliper  I email my CLA for cFE 6.7 and OSAL Thursday (5/7) to GSFC-SoftwareRelease <gsfc-softwarerelease@mail.nasa.gov>. Am I suppose to get an email confirmation?

**Comment by skliper** [comment]
@jtovias Thanks! I'll confirm it was received.

**Comment by astrogeco** [comment]
> @jtovias Thanks! I'll confirm it was received.

@skliper any update on this CLA?

**Comment by skliper** [comment]
Rebased on master and updated commit message.  Still pending OPC CLA confirmation.

**Comment by skliper** [comment]
@astrogeco CLA receipt confirmed.

**Comment by astrogeco** [comment]
@skliper looks like something broke in the CI config.

**Comment by skliper** [comment]
@astrogeco - I just restarted the test and it worked fine.  Looked like a travis-ci issue (not an issue on our side).

**Pull request merged**
