### PR TITLE
Fix #603, Full context info for EVS event stubs

### LINKED ISSUE #603: CFE_EVS_SendEvent stub should provide full context
**Describe the bug**
The CFE_EVS_SendEvent stub for ut-assert does not provide its full context. It only provides the first argument, EventId, providing no way to for unit tests to verify the correct EventType or event message text was sent.

**To Reproduce**
1. See the [CFE_EVS_SendEvent stub](https://github.com/nasa/cFE/blob/60a5f6580d1e737f46efce0418aba5b8dac6df6a/fsw/cfe-core/ut-stubs/ut_evs_stubs.c#L106). Only EventID is registered with the context and copied. 

**Expected behavior**
The CFE_EVS_SendEvent stub should provide its full context for unit testing purposes, including the EventID, EventType, and the event message string. <strike>My preference would be that the event message text provided would not include the format specifiers and instead be the resulting string with the format specifiers replaced with the appropriate text.</strike> I've been convinced and also talked myself out of that preference.

**Code snips**
```
int32 CFE_EVS_SendEvent(uint16 EventID,
                        uint16 EventType,
                        const char *Spec,
                        ...)
{
    int32 status;

    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), &EventID);
    status = UT_DEFAULT_IMPL(CFE_EVS_SendEvent);

    if (status >= 0)
    {
        UT_Stub_CopyFromLocal(UT_KEY(CFE_EVS_SendEvent), (uint8*)&EventID, sizeof(EventID));
    }

    return status;
}
```

**System observed on:**
 - cFE 6.7.11

**Additional context**
n/a

**Reporter Info**
Eric Gilligan NASA/GSFC-5820

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Create a va_list object to capture the full set of variable arguments passed to CFE_EVS_SendEvent and variants (TimedEvent, WithAppID).  Use the variable argument form of the stub implementation to pass all info through to a (possible) hook function.

Fixes #603 

**Testing performed**
Build all unit tests and confirm normal operation, all passing.

**Expected behavior changes**
Hook functions may now use the va_list form and obtain the full context info.

**System(s) tested on**
Ubuntu 20.04

**Additional context**
see also nasa/osal#479, nasa/sample_app#66 for other related enhancements.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
This is currently a draft as it is baselined to the integration-candidate because it conflicts with #673.  Will rebase after next master merge.

In the meantime, only change here for review is commit 4baf092.

**Comment by skliper** [comment]
Are you planning another PR for CFE_ES_WriteToSysLog?

**Comment by jphickey** [comment]
> Are you planning another PR for CFE_ES_WriteToSysLog?

See commit 4cbd761, will squash when I rebase.

**Comment by astrogeco** [comment]
CCB 2020-05-27 APPROVED, @jphickey Create a new issue to refer to items by name.

**Comment by skliper** [comment]
> CCB 2020-05-27 APPROVED, @jphickey Create a new issue to refer to items by name.

Added issue #717

**Comment by astrogeco** [comment]
@jphickey can I remove the draft label?

**Comment by jphickey** [comment]
@astrogeco Rebased to "master', should good to go now.

**Pull request merged**
