### PR TITLE
Fix #422, isTar Implementation

### LINKED ISSUE #422: IsTar Implementation
**Is your feature request related to a problem? Please describe.**
Implement IsTar API

**Requester Info**
Anh Van, NASA Goddard

### PR DESCRIPTION
**Pull request by avan989**
**Describe the contribution**
IsTar implementation. 

**Testing performed**
Steps taken to test the contribution:
1. Modify sample app to call isTar
2. make
3. make install
4. Run and verify result.

**System(s) tested on:**
 - Hardware
 - OS: Ubuntu 18.04
 - CFE 6.6

**Contributor Info**
Anh Van, NASA Goddard

### CODE REVIEW

**Comment by avan989** [comment]
updated.

**Comment by skliper** [comment]
This change actually goes to Beth (likely in cfs_lib or similar), since it's not a cFS framework requirement.

**Comment by astrogeco** [comment]
> This change actually goes to Beth (likely in cfs_lib or similar), since it's not a cFS framework requirement.

Should we just close this and open and have @ejtimmon look at it in the apps repositories?

**Comment by skliper** [comment]
@ejtimmon could you confirm we can close this from the cFE point of view?  Likely more appropriate from the file services library.

**Comment by ejtimmon** [comment]
@skliper Yes, I agree you can close this

**Comment by skliper** [comment]
Marking as invalid with respect to this repo (scope).

**Pull request closed without merging**
