### PR TITLE
Fix #1626, rename/clean CFE coverage assert macros

### LINKED ISSUE #1626: Consistency in CFE coverage test helper macros
**Is your feature request related to a problem? Please describe.**
The following helper macros are defined in `ut_support.h` and used in sb_UT.c, with the intent of applying to other modules:

- SETUP
- ASSERT
- ASSERT_EQ
- ASSERT_TRUE
- EVTCNT
- EVTSENT

These macros are all specific to/tuned toward CFE coverage testing (i.e. they are not generic) because they embed certain CFE patterns/assumptions, i.e. SETUP and TEARDOWN check for CFE_SUCCESS, the "EVENT" macros deal with the UT stub event capture logic, etc.  

**Describe the solution you'd like**
The genuinely CFE-specific macros should be updated with a `CFE_UtAssert_` prefix to indicate that they are assertion statements that are specific to CFE.

For macros which are actually generic, such as "ASSERT_EQ", consider replacing this with the existing generic `UtAssert_INT32_EQ` macro.

Also for wider coverage test applicability and consistency of logging output, should also add the following:

- `VOIDCALL` macro to consistently log functions that do not have a return value, but still want to include the full text of what was called
- `RESOURCEID_EQ` macro to check for equality between resource ID values (INT32_EQ is not sufficient here because one should not assume that IDs are integers)

**Additional context**
Discussed in CCB 2021-06-16, as part of issue #596 and improving the test log output

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Rename CFE coverage test assert macros in ut_support.h to have consistent name prefix.

Also adds a "VOIDCALL" and "RESOURCEID_EQ" macro for logging void functions and ID checks, respectively.

Fixes #1626 

**Testing performed**
Build and run all unit tests

**Expected behavior changes**
None - just renames macros for consistency, and simplifies the implementation of some (reusing existing macro where feasible).

**System(s) tested on**
Ubuntu

**Additional context**
Discussed initially in CCB on 2021-06-16, as part of discussion on #1624, then split off into a separate issue/PR.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
This should be good to go, the "Build cFE documentation" workflow issue is not related, and should be corrected by #1630

**Review by skliper — APPROVED** [review]

**Review by pepepr08 — APPROVED** [review]

**Comment by jphickey** [comment]
After getting into some of the table services use cases, I'm finding it would be better/more useful if these macros had a pass/fail return value like the OSAL ones do.  The problem, particularly with SETUP, is that there is no way to tell if your setup failed and if therefore e.g. a loop should stop.

**Comment by jphickey** [comment]
Re-requesting review, this version seems to work well and I confirmed this set of macros should be sufficient for all CFE core test cases.

Biggest difference between this and the previous set is that the "impl" functions (underneath the macro) return the pass/fail status of the test case as a `bool`.  There are some CFE test cases, particularly in TBL, that need to break out of a loop if setup fails, and this pattern allows that to happen.

Note to reviewers, the actual changes are in `ut_support.h` and `ut_support.c` ... the changes to all other modules in this PR should be a straight search and replace just to use the new macro names, nothing else.  Actual changes/improvement to test cases comes in the next PR.

**Comment by jphickey** [comment]
Pushed again to resolve formatting check issues ....

**Review by pepepr08 — APPROVED** [review]

**Comment by astrogeco** [comment]
DEVS:2021-06-21, We need a "gold standard" way of doing things. 
- the benefit of macros is that they prevents copy-
-paste errors

**Review by skliper — APPROVED** [review]

**Comment by astrogeco** [comment]
[CCB:2021-06-23](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-23-2021) APPROVED

**Pull request merged**
