### PR TITLE
Fix #1692, Add misc time api functional test

### LINKED ISSUE #1692: Add functional tests for cFE Miscellaneous Time APIs
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Miscellaneous Time APIs
    CFE_TIME_Print - Print a time value as a string.
    CFE_TIME_Local1HzISR - This function is called via a timer callback set up at initialization of the TIME service.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

### PR DESCRIPTION
**Pull request by nmullane**
**Describe the contribution**
Fixes #1692 

**Testing performed**
Steps taken to test the contribution:
1. Build and run cfe functional tests

**Expected behavior changes**
- No impact to behavior

**System(s) tested on**
 - Hardware: PC
 - OS: Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Niall Mullane - GSFC 582 Intern

### CODE REVIEW

**Comment by nmullane** [comment]
This PR depends on https://github.com/nasa/osal/pull/1125

**Review by skliper — APPROVED** [review]

**Comment by nmullane** [comment]
I believe this should be passing now. Is there a way to rerun the github action checks?

**Comment by astrogeco** [comment]
@nmullane can you rebase to fix conflicts? That will also re-run the tests. But if you ever want to re run them manually there's 
Screen Shot 2021-08-09 at 5 30 26 PM

**Comment by nmullane** [comment]
> @nmullane can you rebase to fix conflicts? That will also re-run the tests. But if you ever want to re run them manually there's a button for that on the "checks" tab
> 
> Screen Shot 2021-08-09 at 5 30 26 PM

Rebased :+1: 

Also it looks like I don't have the ability to rerun checks.

**Pull request merged**
