### PR TITLE
Fix #1336, function block comments

### LINKED ISSUE #1336: Standardize/clean function description comments
**Is your feature request related to a problem? Please describe.**
They need a general scrub, out of date references, etc.  Example:
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_cds.c#L242-L248

Should clearly indicate implementations that are API's vs internal/helper functions

**Describe the solution you'd like**
Automated cleanup.

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #1350: Move perflog prototypes from `cfe_es_log.h` to `cfe_es_perf.h`
**Is your feature request related to a problem? Please describe.**
Misplaced prototypes:
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_log.h#L322-L326

**Describe the solution you'd like**
Move to `cfe_es_perf.h`

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Fixes #1336 

Scrub all internal APIs within CFE core to make comment blocks in sources and headers more consistent. 

Whenever a function is prototyped in a header, this moves the information about the function behavior to that prototype and puts it into doxygen format.  The comment block on the function implementation refers the reader to the prototype - it does not duplicate the info.  Exception for local helper functions which are not separately prototyped, these may have pre/post condition info in the block itself.

All functions definitions are noted whether they intend to conform to the public API (i.e. from a header in core_api) and therefore have global scope, or if they have application-internal scope, or if they have file/local scope.

**Testing performed**
Build and sanity check CFE, run all unit tests

**Expected behavior changes**
None - documentation updates only

**System(s) tested on**
Ubuntu 20.04

**Additional context**
Changes to each subsystem are put in a separate commit.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

EDIT - also fixes #1350 (deletes instead of moves, they are not implemented)

### CODE REVIEW

**Comment by jphickey** [comment]
Note that in cases where this moved comment info/notes/documentation from the definition to the declaration, it also converted it into doxygen markup where possible.  This takes the first step at putting some doxygen information on every internal API, not just public APIs.  However it does not (yet) fully document all parameters and outputs/return values.  This may show up in the doxygen warnings.  (it was never documented, but now it might be noticed by the tools because it was converted to doxygen style markup).

**Review by skliper — APPROVED** [review]

**Comment by skliper** [comment]
Only nit/recommendation would be not to explicitly reference the header file name the API is defined in.  I'd just put "see header file for full documentation" or similar.  These move around (and will move again when refactored), so easier to keep generic and explicit reference doesn't really provide that much benefit (not worth the effort to keep up-to-date).

**Comment by astrogeco** [comment]
[CCB:2021-04-21](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-April-28-2021) APPROVED
- all comments, some hand edits to docs
- Is there a way to "tell at a glance" what corresponds to public APIs? -> Yes, the file naming pattern and where the header file lives

**Comment by jphickey** [comment]
> Only nit/recommendation would be not to explicitly reference the header file name the API is defined in. I'd just put "see header file for full documentation" or similar. These move around (and will move again when refactored), so easier to keep generic and explicit reference doesn't really provide that much benefit (not worth the effort to keep up-to-date).

See commit a3b8e808 which replaces this to just say "See description in header file ..."

**Comment by jphickey** [comment]
Rebased to latest "main" branch to resolve conflicts.

**Pull request merged**
