### PR TITLE
Fix #815, remove all deprecated code

### LINKED ISSUE #815: Remove CFE deprecated code for next release
**Is your feature request related to a problem? Please describe.**
Now that the "6.8.x" release branch has been created, the next release should remove all code/functions that are currently marked as deprecated.

**Describe the solution you'd like**
Removal of all code currently contained within an `OMIT_DEPRECATED` conditional compile switch.

**Additional context**
The removal only applies to "main" branch - not the 6.7.x release branch, where it will continue to exist for that release series.  This assumes the next release (main) will become version 7.0.

There are other changes currently in development which do break some deprecated items - hence why I'd like to remove this sooner rather than later, as it saves the work of updating/fixing this old code if the intent is to remove it anyway.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
In the next major CFE release, this code will be no longer supported at all.  It should be removed early in the cycle
to avoid needing to maintain this compatibility code.

Fixes #815 

**Testing performed**
Build and run, sanity check CFE.
Run all unit tests.

**Expected behavior changes**
Removes code previously deprecated.
Identical to previous build if the `OMIT_DEPRECATED=true` flag was set during configuration.

**System(s) tested on**
Ubuntu 20.04
RTEMS 4.11.3

**Additional context**
Also depends on nasa/to_lab#55 - should be merged in same cycle.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB 2020-08-19](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-19-2020) Needs more conversation about deprecation timeline and convention

**Comment by skliper** [comment]
@astrogeco - I thought we approved this one?  Further discussion required on the topic of removing elements deprecated this cycle before the release of Caelum.

**Comment by astrogeco** [comment]
> @astrogeco - I thought we approved this one? Further discussion required on the topic of removing elements deprecated this cycle before the release of Caelum.

Fixed CCB comment to reflect approval.

**Comment by yammajamma** [comment]
@jphickey could you please resolve the conflicts here?

**Comment by jphickey** [comment]
Rebased.  Note that this now includes several blocks with a `CFE_OMIT_DEPRECATED_6_8` designation.  These were also removed.  But it may necessitate doing a 6.9 release of some variety.

**Pull request merged**
