### PR TITLE
fix #759 - deprecates GetLastSenderId()

### LINKED ISSUE #608: CFE_SB_GetLastSenderID returns pointer to internal data, possible race
**Describe the bug**
CFE_SB_GetLastSenderID returns pointer to data that could be overwritten at any time

See https://github.com/nasa/cFE/pull/605#discussion_r407649126 for related comments

**To Reproduce**
Conceptually - app calls CFE_SB_GetLastSenderID, gets pointer, data gets overwritten, app takes action based on overwritten data vs original context

**Expected behavior**
No race.

**Code snips**
https://github.com/nasa/cFE/blob/60a5f6580d1e737f46efce0418aba5b8dac6df6a/fsw/cfe-core/src/sb/cfe_sb_api.c#L1651-L1657

**System observed on:**
N/A

**Additional context**
#605

**Reporter Info**
Jacob Hageman

### LINKED ISSUE #759: remove GetLastSenderId() API and replace with a RecvMsg() API that returns the AppId of the sender of the message being received
**Describe the bug**
The current CFE_SB_GetLastSenderId() API is broken, as indicated in #745 and #744, but also as discussed at today's CCB, the intent and use-case is really "who sent *this* message" not "who sent the *last* message" on a pipe. In fact, SBN is currently using this API to prevent SBN message loops, and this API doesn't work correctly for that purpose.

**Expected behavior**
The suggestion is to remove the GetLastSenderId() API entirely, and add a new receive method like: `int32  CFE_SB_RcvMsgWithSenderId(CFE_SB_MsgPtr_t  *BufPtr, uint32 *SenderAppIdPtr, CFE_SB_PipeId_t  PipeId, int32 TimeOut);` that has an additional out parameter which will contain the AppId of the app that sent the message returned in the BufPtr.

**Reporter Info**
Christopher.D.Knight@nasa.gov

### PR DESCRIPTION
**Pull request by CDKnightNASA**
**Describe the contribution**
Fixes #759 - deprecates CFE_SB_GetLastSenderId() API.
Fixes #608

**Testing performed**
make with and without OMIT_DEPRECATED defined.

**System(s) tested on**
Debian 10.3

**Contributor Info - All information REQUIRED for consideration of pull request**
Christopher.D.Knight@nasa.gov

### CODE REVIEW

**Comment by jphickey** [comment]
Another note - I believe for other APIs that have been deprecated, rather than clutter up the unit test code with `#ifdef` directives - we can just remove it outright, as (AFAIK) there is no requirement to unit test deprecated functions.  UT code is ugly enough already.

**Comment by CDKnightNASA** [comment]
> Looks OK to me.
> 
> Two minor nitpicks though:
> 
> * The existing `OMIT_DEPRECATED` flags have a CFE prefix.

Whoop, don't know how I missed this!

> * Also if introducing a new deprecation we need to add it to the global_build_options.cmake file so it gets turned on with OMIT_DEPRECATED=true like the others do.

Copy.

I've squashed updates.

**Comment by CDKnightNASA** [comment]
> Another note - I believe for other APIs that have been deprecated, rather than clutter up the unit test code with `#ifdef` directives - we can just remove it outright, as (AFAIK) there is no requirement to unit test deprecated functions. UT code is ugly enough already.

Done, the stubs remain (of course) but are likewise #ifndef'd.

**Comment by skliper** [comment]
Moved the requirement back to "submitted" in requirement tracking tool.  Will need to export and update text requirements.

**Comment by CDKnightNASA** [comment]
> Moved the requirement back to "submitted" in requirement tracking tool. Will need to export and update text requirements.

Would it be worthwhile to export the requirements into an integrated requirements tracking system, like https://pypi.org/project/doorstop/ ?

**Comment by astrogeco** [comment]
CCB 2020-07-29, APPROVED, @skliper to provide doxygen deprecation example.

**Comment by astrogeco** [comment]
@CDKnightNASA can you move the cmake 6_8 definition into it's own commit?

**Comment by skliper** [comment]
Example of deprecated doxygen markings:
https://github.com/nasa/cFE/blob/deeb2942b0766a87d7b399bd8c11c2d5c8deffc0/fsw/cfe-core/src/inc/cfe_fs.h#L194-L214

**Comment by gerycruz** [comment]
> > Moved the requirement back to "submitted" in requirement tracking tool. Will need to export and update text requirements.
> 
> Would it be worthwhile to export the requirements into an integrated requirements tracking system, like https://pypi.org/project/doorstop/ ?

I looked into it and it looks interesting but I'm not sure what it buys us. Have you used it?

**Comment by skliper** [comment]
Would need to trade against the internal tools and process requirement compliance.  We get some things for "free" using standard internal processes, but that doesn't mean it's better.

**Comment by CDKnightNASA** [comment]
> > > Moved the requirement back to "submitted" in requirement tracking tool. Will need to export and update text requirements.
> > 
> > 
> > Would it be worthwhile to export the requirements into an integrated requirements tracking system, like https://pypi.org/project/doorstop/ ?
> 
> I looked into it and it looks interesting but I'm not sure what it buys us. Have you used it?

I have not, but some folks at the 2019 FSW mentioned they used it. Certainly would need to do a study of it.

**Comment by CDKnightNASA** [comment]
> @CDKnightNASA can you move the cmake 6_8 definition into it's own commit?

done

**Comment by CDKnightNASA** [comment]
> CCB 2020-07-29, APPROVED, @skliper to provide doxygen deprecation example.

done, ready for review again

**Comment by astrogeco** [comment]
@skliper this looks good to me, are we good to merge?

**Comment by skliper** [comment]
Can this go in the 6.8 dev cycle?  It's wrapped with the 6.8 omit define.  Other than that, yes looks good to me.

**Comment by astrogeco** [comment]
> Recommend merge to 6.8 development

If you you mean make this part of 6.8 then yes!

**Comment by skliper** [comment]
No, I mean development on top of 6.8.  Otherwise the OMIT numbering breaks convention.  I'm requesting making the rc tags BEFORE merging this change.

**Comment by skliper** [comment]
Marked my preference as targeting this for 7.0 release.  Sorry, my quick comments weren't very clear.

**Comment by astrogeco** [comment]
The milestone helps, thanks!

**Comment by astrogeco** [comment]
What's the convention then? Should the deprecate tag then say deprecate 7_0 or 7_1?

**Comment by skliper** [comment]
> What's the convention then? Should the deprecate tag then say deprecate 7_0 or 7_1?

6_8.

**Comment by astrogeco** [comment]
> > What's the convention then? Should the deprecate tag then say deprecate 7_0 or 7_1?
> 
> 6_8.

For completeness then, does DEPRECATE_6_8 means that 6.8 was the last version which supports this function?

**Comment by skliper** [comment]
We've typically just marked with the last released version, so it could be interpreted that way but I'm not aware of any hard rules or published deprecation process.  See nasa/cFS#67.

**Comment by jphickey** [comment]
> does DEPRECATE_6_8 means that 6.8 was the last version which supports this function?

Yes, that is the paradigm we've been using up to this point -- the number reflects the last release were it was _not_ deprecated.  The idea of putting a version number in the tag was so we'd know which ones had "aged out" in a future release and should be taken out completely.  

However as I mentioned before now that we have a codename for API compatibility then maybe we should consider using that instead.

**Comment by astrogeco** [comment]
@CDKnightNASA does this actually fix #608? Just wondering since you don't mention it in the commits

**Comment by CDKnightNASA** [comment]
> @CDKnightNASA does this actually fix #608? Just wondering since you don't mention it in the commits

Yes it fixes #608.

**Pull request merged**
