### PR TITLE
Use SRC_LOCAL_PATH as single source of truth

### PR DESCRIPTION
**Pull request by matzipan**
This avoids the two path diverging and possibly causing problems in the future

**Describe the contribution**
The call to `file(TO_NATIVE_PATH ...)` is building its own path even though its contents are identical to `SRC_LOCAL_PATH`. This change avoids possible divergence of these values in the future.

**Testing performed**
Ran a local build.

**Expected behavior changes**
No change in behavior.

### CODE REVIEW

**Comment by stanislaw** [comment]
Please note, that PTS GmbH has signed the corporate CLA document on Feb 17th and it has been sent to the GSFC-SoftwareRelease email. @matzipan is on the list so this PR should no longer be pending CLA.

cc @skliper

**Comment by skliper** [comment]
CLA confirmed, this pull request can proceed.

**Comment by astrogeco** [comment]
@matzipan and @stanislaw please update the the title of your pull requests and your commits to use the following format: 

`Fix #ISSUE_NUMBER, Description`

see other pull requests and commits in repository as an example.

**Comment by astrogeco** [comment]
CCB 20200311 - Approved

**Comment by matzipan** [comment]
Apologies for not having time to change the title format to `Fix #ISSUE_NUMBER, Description`. I'm guessing it might be a bit late now.

**Comment by astrogeco** [comment]
> Apologies for not having time to change the title format to `Fix #ISSUE_NUMBER, Description`. I'm guessing it might be a bit late now.

No worries. We don't have a contribution guide up so you had no way to know in advance. In the future please open an issue and then the pull request to address it; this helps us build our version description document when we do our next release.

**Pull request merged**
