### PR TITLE
Fix #651, Use resource ID for memory pools

### LINKED ISSUE #651: CFE_ES_SEND_MEM_POOL_STATS_CC Issues
**Describe the bug**
There are multiple issues with the CFE_ES_SEND_MEM_POOL_STATS_CC command:
1.	The command/function(s) used are fundamentally flawed in that a user can send a seemingly benign command that can result in a segmentation fault if one of the command parameters is incorrect.  For example, if the PoolHandle parameter is set to zero a segmentation fault will result (pretty much any value below xFFFFFE28 faults on my machine).  This occurs when handle is validated via the CFE_ES_ValidateHandle function.  Should consider modifying the CFE_ES_ValidateHandle function + updating the unit test to test command on boundary/extreme conditions.
2.	On a 64-bit machine if the PoolHandle parameter is set to a valid value the function will fail.  This is because CFE_PSP_MemValidateRange – which is called via the CFE_ES_ValidateHandle function as part of the validation process, limits the max memory range of the handle to xFFFFFFFE.
3.	On a 64-bit machine - compiler added padding will be applied to the command.  The order of variable declaration should ideally be descending in size to avoid future conflicts.

**Expected behavior**
Command works nominally and is vetted via combination of unit/functional tests.

**System observed on:**
Oracle VM VirtualBox
OS: ubuntu-19.10
Versions: cFE 6.7.13.0, OSAL 5.0.12.0, PSP 1.4.9.0

**Reporter Info**
Dan Knutsen
NASA/Goddard

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**

Instead of identifying a memory pool by its memory address, use a resource ID.  IDs are a constant size, regardless of
whether the host machine is 32 or 64 bits.

- IDs can be put into commands/telemetry and maintain a more consistent format with consistent alignment requirements.
- IDs can be independently verified without dereferencing memory.  Previously the only way to validate a memory pool was to read the address pointed to, which results in a segfault if the address was bad.

Fixes #651 

**Testing performed**
Build and sanity test CFE, run all unit tests
Confirm code coverage up to par.

**Expected behavior changes**
The `CFE_ES_MemHandle_t` type is no longer a direct CPU address.  Instead it is an abstract resource identifier.
This should fix issues with unexpected padding of CMD/TLM messages that contain memory pool handles.

**System(s) tested on**
Ubuntu 20.04
RTEMS 4.11

**Additional context**
Fairly extensive changes in the memory pool implementation to support abstract handles, but the API exposed to applications should be backward compatible, so long as apps did not rely on the specific pool layout.

The downside is that there is a limit to the total number of abstract identifiers that can exist, which is a new platform config limit.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Confirmed this also fixes #854

**Comment by astrogeco** [comment]
[CCB 2020-09-30](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-30-2020):
- Creates a memory pool implementation that mirrors how we handle other abstract resources 
APPROVED

**Comment by astrogeco** [comment]
@jphickey is #854 the issue we discussed opening at the CCB?

**Comment by jphickey** [comment]
> @jphickey is #854 the issue we discussed opening at the CCB?

No, the old issue about CDS mempool is in #56 ... it has been on the to-do list for about 5 years.

**Pull request merged**
