### PR TITLE
Fix #1997, Mismatched foreach in cmake function

### LINKED ISSUE #1997: Mismatched foreach in cmake function
The endforeach args do not match the foreach args

  foreach(APP ${MISSION_DEPS})
    list(APPEND VARLIST "${APP}_MISSION_DIR")
  endforeach(APP ${**MISSION_APPS**})

https://github.com/nasa/cFE/blob/98f78e8604c19415fd1e199eae94196a781539b8/cmake/mission_build.cmake#L362

### PR DESCRIPTION
**Pull request by paulober**
**Describe the contribution**
- Fixes #1997

**Additional context**
-> conversation at #1997 

**Contributor Info - All information REQUIRED for consideration of pull request**
Personal

### CODE REVIEW

**Comment by skliper** [comment]
Recommendation is to remove the arguments.

**Comment by pavll** [comment]
I know, I mentioned it in the issue but no response... I'll fix this in my PR.

**Comment by astrogeco** [comment]
> I know, I mentioned it in the issue but no response... I'll fix this in my PR.

thanks! We typically are a bit more responsive on PRs though this month has been hectic so our response time has been slower than usual. We appreciate your help!

**Comment by pavll** [comment]
> > I know, I mentioned it in the issue but no response... I'll fix this in my PR.
> 
> thanks! We typically are a bit more responsive on PRs though this month has been hectic so our response time has been slower than usual. We appreciate your help!

Ok, no problem. I'm grateful to be able to work on this project.

**Review by skliper — APPROVED** [review]

**Comment by astrogeco** [comment]
[CCB:2021-12-08](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-December-08-2021) - APPROVED

**Pull request merged**
