### PR TITLE
Fix #909, reorganize ES public API + msg definitions

### LINKED ISSUE #909: Move typedefs used in cmd/tlm to the *_msg.h file
**Is your feature request related to a problem? Please describe.**
CFE_ES_AppInfo_t and CFE_ES_MemHandle_t are defined in cfe_es.h, but used in telemetry (cfe_es_msg.h).  All the typedefs used in telemetry should be defined in the *_msg.h file.

**Describe the solution you'd like**
Move CFE_ES_AppInfo_t and CFE_ES_MemHandle_t into cfe_es_msg.h

Note CFE_ES_TaskInfo_t is not used in cmd/tlm.

**Describe alternatives you've considered**
None

**Additional context**
Related to #899

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**

Put all ES typedefs which are shared across API and telemetry messages into the `cfe_es_extern_typedefs.h` file.

Put all ES typedefs which define the telemetry interface into the `cfe_es_msg.h` file.  Also include structures which define the output of commands that write data files into this group (query all apps, query all tasks, query all CDS).

Removes some localized definitions and replace with MISSION scope definitions where appropriate/necessary.

Fixes #909 

**Testing performed**
Build and sanity check CFE
Run all unit tests

**Expected behavior changes**
No impact to behavior
(Should not change any binary formats)

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Review by acudmore — APPROVED** [review]
Changes look good to me, nice improvements for consistency.

**Comment by jphickey** [comment]
Adding commits to fix two other minor issues

Fixes #964 via commit d21d94a
Fixes #370 via commit f9f18a7

**Comment by astrogeco** [comment]
[CCB 2020-10-28](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-October-28-2020) APPROVED
- Consider moving bool in cfe_es_msg
- Discuss with Walt

**Comment by astrogeco** [comment]
[CCB 2020-10-28](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-October-28-2020) APPROVED

**Comment by skliper** [comment]
Discussed at splinter, moving bool didn't sound like it would be an issue.

**Pull request merged**
