### PR TITLE
Fix #766, Add to table search path

### LINKED ISSUE #766: Add to table search path... either point solution or general
**Is your feature request related to a problem? Please describe.**
Power users have had to clone and own the cmake logic for adding tables to implement preferred directory structure and naming patterns in searching for the table files.  Currently not a good way (that I know of) to customize:

https://github.com/nasa/cFE/blob/a47abba14b7e8ffbc8c8e78614babdb151412af2/cmake/arch_build.cmake#L128-L140

**Describe the solution you'd like**
Some way to customize the search path... or we could just do a point solution where we add the desired search path for this stakeholder.

if (EXISTS "${MISSION_DEFS}/${TGT}/tables/${TBLWE}.c")

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Adds to table search path
Fix #766

**Testing performed**
CI

**Expected behavior changes**
Just adds to search path

**System(s) tested on**
CI

**Additional context**
None

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by skliper** [comment]
@jphickey @astrogeco could we add this one in?  stakeholder request.

Ping @excaliburtb

**Comment by skliper** [comment]
> Once PR #751 is merged then I'd suggest adding a table search path to mission_defaults.cmake to allow customization of this table search path. It is a little more complicated than the app search path as it needs to be per-cpu but I think it can be done.

The table search path in mission_defaults.cmake would be the ideal solution in my mind.  I really think moving the various search paths to mission_defaults.cmake is a significant improvement in general.

**Comment by excaliburtb** [comment]
Are you waiting on me for anything? I'd like to get this in to at least IC branch and the solution looks fine to me.

**Comment by skliper** [comment]
Whoops, I thought this was in IC... @astrogeco could we get this added?

**Pull request merged**
