### PR TITLE
Fix #596, scrub all UT_Report calls

### LINKED ISSUE #470: Incomplete coverage test for src/fs
**Is your feature request related to a problem? Please describe.**
Current coverage 91.3%

Missing coverage for the following: cfe_fs_decompress.c

FS_gz_eat_header_Reentrant
```
     214           2 :                 if ( (flags & CONTINUATION) != 0 ) {
     215           0 :                         NEXTBYTE();
     216           0 :                         if( State->Error != CFE_SUCCESS ) return CFE_FS_GZIP_READ_ERROR_HEADER;
     217           0 :                         NEXTBYTE();
     218           0 :                         if( State->Error != CFE_SUCCESS ) return CFE_FS_GZIP_READ_ERROR_HEADER;
     219             :                 }
     220             :                 
     221           2 :                 if ( (flags & EXTRA_FIELD) != 0 ) {
     222             :                         uint32 len;
     223           0 :                         len  = NEXTBYTE();
     224           0 :                         if( State->Error != CFE_SUCCESS ) return CFE_FS_GZIP_READ_ERROR_HEADER;
     225           0 :                         len |= NEXTBYTE() << 8;
     226           0 :                         if( State->Error != CFE_SUCCESS ) return CFE_FS_GZIP_READ_ERROR_HEADER;
     227           0 :                         while (len--) {
     228           0 :                                 NEXTBYTE();
     229           0 :                                 if( State->Error != CFE_SUCCESS ) return CFE_FS_GZIP_READ_ERROR_HEADER;
     230             :                         }
```

```
     251           0 :                         keep_going = true;
     252           0 :                         while ( keep_going ) {
     253             : 
     254             :                                 /* Get the next byte */
     255           0 :                                 thisByte = NEXTBYTE();
     256             : 
     257             :                                 /* Header failure when end of file is reached or a read failure occurs */
     258           0 :                                 if ((thisByte == EOF) || (State->Error != CFE_SUCCESS)) return CFE_FS_GZIP_READ_ERROR_HEADER;
     259             : 
     260             :                                 /* End of string was found */
     261           0 :                                 if (thisByte == 0) keep_going = false;
```

FS_gz_huft_build_Reentrant

```
     399           0 :                 *m = 0;
     400           0 :                 return CFE_SUCCESS;
```

```
     529             :                         {
     530           0 :                                 return CFE_FS_GZIP_BAD_CODE_BLOCK;
```

```
     583           0 :                 State->bk -= 8;
     584           0 :                 State->inptr--;
```

`     634           0 :         else               res = CFE_FS_GZIP_BAD_CODE_BLOCK;    `

`     689           0 :                  return CFE_FS_GZIP_INDEX_ERROR;`

```
     703           0 :             State->outcnt = w;
     704           0 :             FS_gz_flush_window_Reentrant(State);
     705           0 :             w = 0;
```

`     736           0 :                   return CFE_FS_GZIP_INDEX_ERROR;`

FS_gz_inflate_dynamic_Reentrant

```
     928           0 :          NEEDBITS(7);
     929           0 :          j = 11 + ( (uint32)b & 0x7f );
     930           0 :          DUMPBITS(7);
     931           0 :          if ( (uint32)i + j > n ) return CFE_FS_GZIP_BAD_DATA;
     932           0 :          while (j--) ll[i++] = 0;
     933           0 :          l = 0;
```

FS_gz_inflate_stored_Reentrant

```
    1053           0 :         n = ( (uint32)b & 0xffff );
    1054           0 :         DUMPBITS(16);
    1055             : 
    1056           0 :         NEEDBITS(16);
    1057           0 :         if ( n != (uint32)( (~b) & 0xffff) )  return CFE_FS_GZIP_BAD_DATA;    /* error in compressed data */
    1058           0 :         DUMPBITS(16);
    1059             : 
    1060             : 
    1061             :         /*  read and output the compressed data */
    1062           0 :         while (n--) 
    1063             :    {
    1064           0 :                 NEEDBITS(8);
    1065           0 :       State->window[w++] = (uint8)b;
    1066           0 :                 if ( w == WSIZE ) 
    1067             :       {
    1068           0 :                 State->outcnt = w;
    1069           0 :                 FS_gz_flush_window_Reentrant(State);
    1070           0 :                 w = 0;
    1071             :                 }
    1072           0 :                 DUMPBITS(8);
    1073             :         }
    1074             : 
    1075             :         /*  restore the globals from the locals */
    1076           0 :         State->outcnt = w;                                   /* restore global window pointer */
    1077           0 :         State->bb     = b;                                   /* restore global bit buffer */
    1078           0 :         State->bk     = k;
    1079             : 
    1080           0 :         return CFE_SUCCESS;
```

**Requester Info**
Anh Van, NASA Goddard

### LINKED ISSUE #596: Unit test - split "AND"-ed conditionals into separate asserts
**Is your feature request related to a problem? Please describe.**
Debugging unit tests can be very difficult, frustrating, and time consuming.  One major part of the problem which makes them very debugging-unfriendly is something like the following:

```
    UT_Report(__FILE__, __LINE__,
              UT_EventIsInHistory(CFE_ES_PCR_ERR2_EID) &&
              CFE_ES_Global.AppTable[Id].ControlReq.AppTimer == 0 &&
              CFE_ES_Global.AppTable[Id].ControlReq.AppControlRequest == CFE_ES_RunStatus_SYS_DELETE,
              "CFE_ES_ScanAppTable",
              "Waiting; process control request");
```

The problem with this type of construct is that there are 3 separate tests being combined into one single assert.  When it fails, it is not possible to see which of the three conditions are evaluating false.  Many of them call functions within the test case, too, which further obfuscate what the actual return value was.  The only way to test this is run it in a debugger, break at the start of the test, then set a breakpoint inside e.g. UT_EventIsInHistory to see what it returned.

**Describe the solution you'd like**

1. At a minimum - split the `&&` conditions into separate asserts.  This would _at least_ let the developer know which one is actually the fault.  
2. Nice to have - employ the macros similar to what @CDKnightNASA added in nasa/osal#405, which show the _values_ tested in the log, not simply just a pass/fail.

**Describe alternatives you've considered**
Continue struggling to figure out what actually went wrong every time a UT failure comes up.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Scrub through all UT reporting calls and replace with preferred macro where possible.

- All calls to check status/return code are replaced with macro that logs all arguments and return value
- All calls that involved multiple conditions AND'ed together are replaced with individual asserts on each condition.

Fixes #596
Fixes #470 

**Testing performed**
Build and run unit tests, confirm logging is as intended, and coverage level is not reduced

**Expected behavior changes**
Better, more complete context information is logged into the file
All individual assert conditions are logged separately (no more checking of multiple AND'ed values/conditions in a single report)

**System(s) tested on**
Ubuntu

**Additional context**
This also removes all the "free-form" info that was in the logs, since it wasn't really providing value (a developer will go to the source file/line number and see full context, nor was it complete or consistent enough to provide any value for cross referencing or documentation).

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Pushing as draft for initial review/discussion, only "ES" module is done so far.

**Comment by astrogeco** [comment]
[CCB:2021-06-16](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-16-2021) APPROVED
- There's a Ressource ID equal macro in cfe_test.h
- Should we take out the notice of how the test failed?
- What to do with the macros' prefixes? Keep them, having the prefix indicates that it is not part of the generic UTAssert set

**Comment by jphickey** [comment]
Updated for review.  This is based on the current "integration-candidate" (pending final baseline) but otherwise is ready to go.

**Review by skliper — APPROVED** [review]

**Review by pepepr08 — APPROVED** [review]

**Comment by jphickey** [comment]
Added commit to fix #470 onto this PR to avoid conflict/baseline issue, as the FS test changes would not merge cleanly with the other scrub.

This gets 100% line and 100% function coverage, and about 96% branch coverage.  There are 5 untested branches total, 4 of which are "Endian Check" therefore fixed in hardware (not possible to change except by running on other arch).  The last flagged item was the while loop with two OR'ed conditions, they typically both become false at the same time, there is never a way in the current code that only the second condition will be false, but I prefer to keep both stop conditions just in case.

**Comment by skliper** [comment]
@astrogeco - AFAIK this should either be merged with IC or a discussion topic at the CCB?

**Comment by astrogeco** [comment]
Put it on the agenda, didn't merge because of draft status

**Comment by astrogeco** [comment]
[CCB:2021-06-23](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-23-2021) 
- LESSON LEARNED: do not use a single assert for multiple things. This obfuscates things if there's actual problems. Use one condition per assert!

**Pull request merged**
