### PR TITLE
Fix #2410, document ES Perf enums

### LINKED ISSUE #2410: Values for TriggerMode provided to CFE_ES_StartPerfCmd are not documented
**Describe the bug**

Here is the documentation for the `CFE_ES_StartPerfCmd_Payload` struct:

> 10.39.2.1 TriggerMode `uint32 CFE_ES_StartPerfCmd_Payload::TriggerMode`
> Desired trigger position (Start, Center, End)
> Definition at line 279 of file `default_cfe_es_msgstruct.h`

There is no indication what values correspond with `Start`, `Center`, and `End`.

Some searching reveals that the implementation in `modules/es/fsw/src/cfe_es_perf.c` compares for values `CFE_ES_PERF_TRIGGER_{START,CENTER,END}`. The public header `/modules/es/fsw/src/cfe_es_perf.h` has the enum values for this, but there is no docstring and therefore does not appear in the user guide. The actual default numeric values would be good to indicate somewhere because the commanding interface may not have access to the `CFE_ES_PERF_TRIGGER*` macros, ie, when using `cmdUtil` from the command line.

**Reporter Info**
Isaac Rowe, NASA JSC, Jacobs Technology

### PR DESCRIPTION
**Pull request by irowebbn**
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFE/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
A clear and concise description of what the contribution is.
- Fixes #2410

**Expected behavior changes**
 - No impact to behavior (doc change)

**Contributor Info - All information REQUIRED for consideration of pull request**
Isaac Rowe, NASA JSC, Jacobs Technology

### CODE REVIEW

**Comment by irowebbn** [comment]
I'm having trouble rebuilding the user's guide, so I may need assistance with that for testing.

**Comment by dzbaker** [comment]
@irowebbn We're getting some workflow failures on building documentation now. Would you be able to resolve those?

**Comment by irowebbn** [comment]
@skliper , I haven't been able to replicate the cfe-userguide failure locally.

**Comment by jphickey** [comment]
The issue here was a bit more subtle, not just a mismatched ID.

The API documentation only uses the _public_ headers - not the private ones.  The "perf" enum was defined in a private header.  This really means that the enum was in the wrong place, its actually part of the public API, not a private type.

Moving the perf enum definition solves the problem.

**Comment by jphickey** [comment]
The only test "failing" now was the format checks.... trying to fix that....

**Comment by jphickey** [comment]
@dzbaker - should be good to merge now.
I also submitted #2477 ... the failure of that workflow is a nuisance.

**Review by jphickey — APPROVED** [review]

**Pull request merged**
