### PR TITLE
Partial #1724, update in/out status and nonnull/nonzero tags

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
First pass at API doxygen scrub, this updates the in/out markings on parameters where they were not correct, and adds nonnull and nonzero tags where appropriate.

Related to #1724 (but should not close yet)

**Testing performed**
Build and run all tests

**Expected behavior changes**
None (documentation only)

**System(s) tested on**
Ubuntu

**Additional context**
Note this is "partial" as it does not yet do all the test case verification, those will come later.  But the API documentation needs to have these tags correct so the validation scripts know what to look for.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Review by skliper — APPROVED** [review]

**Review by skliper — CHANGES_REQUESTED** [review]
Should #1762 be fixed here?

**Comment by jphickey** [comment]
> Should #1762 be fixed here?

I will submit something specifically for #1762, since it was already written up as a separate issue.  I actually backed out the `@nonnull` tag on that one for this PR (that was incorrect).  I had actually done this change 2-3 weeks ago, but I hadn't submitted the PR.

**Comment by jphickey** [comment]
Note, I found/fixed a bug in my script that was causing it to not find all the return status codes correctly.  Will be pushing an update based on a new run.

**Comment by astrogeco** [comment]
[CCB:2021-08-11](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-11-2021)

**Review by skliper — APPROVED** [review]

**Pull request merged**
