### PR TITLE
Fix #2378, refactor SB to support additional use cases

### LINKED ISSUE #2378: Software bus refactoring needed to prepare for future needs
**Is your feature request related to a problem? Please describe.**
Requests have been received for software bus features such as:

 - Better Message integrity checking
 - Better control over message routing and delivery
 - Timestamped commands (not just TLM)

**Describe the solution you'd like**
The software bus can support all of this but the internal workings need some refactoring and clean up to make it possible to fully integrate such features without duplicating the code.

**Describe alternatives you've considered**
N/A

**Additional context**
Breaking up the software bus functions into smaller bits of functionality allow for:
 
- Different transmit/receive variants to use the same basic logic
- Easier unit testing and maintenance of smaller routines
- Reduced cyclomatic complexity of smaller routines
- More code re-use between the two

This needs to be implemented before #2362 can be done.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFE/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Cleans up the internal SB implementation so it can better support future enhancements such as message integrity, additional header fields and timestamping.

Fixes #2378

**Testing performed**
Full suite of tests on SB implementation

**Expected behavior changes**
API behavior is preserved, fully backward compatible

**System(s) tested on**
Debian 

**Additional context**
Replaces #2367 based on code review and discussion.  This PR represents the refactoring change, along with some other refinements.  The routing change will be a separate PR.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Rebased this PR to current main branch

**Comment by jphickey** [comment]
The unused variable static analysis warning is fixed, but code coverage is now complaining.  

The "missed branches" that it is reporting are mostly due to the fact that the `switch` statements in the code only have cases for the values that actually occur, and thus it is impossible to reach the switch with a value that doesn't have a case for it.  While this would normally be a good thing, gcov/lcov flags it as an uncovered branch.  I will look into this tomorrow to see if I can resolve it somehow.

**Comment by jphickey** [comment]
Most "switch" cases now fixed (code coverage-wise) by adding a default case that does nothing, and always going through it.  Looking at other modules there are still some code coverage lines that could potentially be fixed up before merging.

**Comment by dzbaker** [comment]
CCB 2 May 2024: Approved pending BVT run.

**Pull request merged**
