### PR TITLE
Fix #1743, update coverage test to use UtAssert macros

### LINKED ISSUE #1743: Transition CFE tests to use UtAssert macros (moved from CFE)
**Is your feature request related to a problem? Please describe.**
In pull request nasa/osal#1125, a number of CFE coverage assert macros and generic functions were ported into the base UtAssert library.  Usage of the macro is equivalent.

**Describe the solution you'd like**
After merging that PR, remove the local CFE definitions of the macros and functions, and search/replace all references to use the UtAssert version instead.

**Describe alternatives you've considered**
Leave duplicate

**Additional context**
Requires nasa/osal#1125 to be merged first (or at the same time)

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
A number of CFE coverage-specific macros and generic assert functions were moved into OSAL UtAssert library so it can be used in a wider variety of tests.

This removes the CFE coverage-specific version, and changes allreferences to use the equivalent UtAssert macro.

Fixes #1743

**Testing performed**
Build and run all tests

**Expected behavior changes**
None - UtAssert-provided macros should be equivalent in function

**System(s) tested on**
Ubuntu

**Additional context**
Requires nasa/osal#1125

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Marking as ready for review, although the CI test is reporting as failing now, it should work just fine once nasa/osal#1125 is in.

**Review by skliper — APPROVED** [review]

**Review by zanzaben — CHANGES_REQUESTED** [review]
cFE_FTAssert_VOIDCALL from cfe_test.h can be replaced by the new UtAssert_VOIDCALL

**Comment by astrogeco** [comment]
[CCB:2021-08-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-04-2021) Wait until next week

**Comment by astrogeco** [comment]
> cFE_FTAssert_VOIDCALL from cfe_test.h can be replaced by the new UtAssert_VOIDCALL

Opening new issue for this

**Pull request merged**
