### PR TITLE
Add table api functional tests

### LINKED ISSUE #1685: Add functional tests for cFE Table Registration APIs
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Table Registration APIs
    CFE_TBL_Register - Register a table with cFE to obtain Table Management Services.
    CFE_TBL_Share - Obtain handle of table registered by another application.
    CFE_TBL_Unregister - Unregister a table.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

### LINKED ISSUE #1686: Add functional tests for cFE Manage Table Content APIs
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Manage Table Content APIs
    CFE_TBL_Load - Load a specified table with data from specified source.
    CFE_TBL_Update - Update contents of a specified table, if an update is pending.
    CFE_TBL_Validate - Perform steps to validate the contents of a table image.
    CFE_TBL_Manage - Perform standard operations to maintain a table.
    CFE_TBL_DumpToBuffer - Copies the contents of a Dump Only Table to a shared buffer.
    CFE_TBL_Modified - Notify cFE Table Services that table contents have been modified by the Application.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

### LINKED ISSUE #1687: Add functional tests for cFE Access Table Content APIs
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Access Table Content APIs
    CFE_TBL_GetAddress - Obtain the current address of the contents of the specified table.
    CFE_TBL_GetAddresses - Obtain the current addresses of an array of specified tables.
    CFE_TBL_ReleaseAddress - Release previously obtained pointer to the contents of the specified table.
    CFE_TBL_ReleaseAddresses - Release the addresses of an array of specified tables.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

### LINKED ISSUE #1688: Add functional tests for cFE Get Table Information APIs
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Get Table Information APIs
    CFE_TBL_GetStatus - Obtain current status of pending actions for a table.
    CFE_TBL_GetInfo - Obtain characteristics/information of/about a specified table.
    CFE_TBL_NotifyByMessage - Instruct cFE Table Services to notify Application via message when table requires management.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

### PR DESCRIPTION
**Pull request by nmullane**
**Describe the contribution**
A clear and concise description of what the contribution is.
- Fixes
  - Fix #1685
  - Fix #1688 
  - Fix #1686 
  - Fix #1687 
- Adds functional unit tests for
  - CFE_TBL_Register
  - CFE_TBL_Share
  - CFE_TBL_Unregister
  - CFE_TBL_GetStatus
  - CFE_TBL_GetInfo
  - CFE_TBL_NotifyByMessage
  - CFE_TBL_Load
  - CFE_TBL_Update
  - CFE_TBL_Validate
  - CFE_TBL_Manage
  - CFE_TBL_DumpToBuffer
  - CFE_TBL_Modified
  - CFE_TBL_GetAddress
  - CFE_TBL_GetAddresses
  - CFE_TBL_ReleaseAddress
  - CFE_TBL_ReleaseAddresses

**Testing performed**
Steps taken to test the contribution:
1. Build CFE and run all functional tests

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - no impact to behavior

**System(s) tested on**
 - Hardware: PC
 - OS: Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Niall Mullane - GSFC 582 Intern

### CODE REVIEW

**Comment by zanzaben** [comment]
This needs to wait until #1752 merged

**Comment by astrogeco** [comment]
[CCB:2021-08-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-04-2021) APPROVED
- also check that "ToIndex" is less than maximum in CounterID

**Comment by skliper** [comment]
Need to link to the PR's...

**Comment by astrogeco** [comment]
> Need to link to the PR's...

@nmullane can you add "Fix #" to each bullet at the top of the description? GitHub doesn't catch it otherwise

**Comment by astrogeco** [comment]
Failing Test Passes in integration-candidate see fork
https://github.com/astrogeco/cFE/actions?query=branch%3Aic-2021-08-10++

**Pull request merged**
