### PR TITLE
Fix #1474, #1552, Resolve API prototype/implementation discrepancies

### LINKED ISSUE #1474: API Prototype/implementation mismatch scrub
**Is your feature request related to a problem? Please describe.**
Example from `CFE_MSG_Init`, `CFE_Status_t` vs int32:
https://github.com/nasa/cFE/blob/c8b5e00bb722d8f59787ae8f82634feba5d39f60/modules/msg/fsw/src/cfe_msg_init.c#L32
https://github.com/nasa/cFE/blob/c8b5e00bb722d8f59787ae8f82634feba5d39f60/modules/core_api/fsw/inc/cfe_msg.h#L63

Note numerous others, some noted in TBL.

**Describe the solution you'd like**
General scrub, prototypes across all the headers should match implementation.  Also could remove `extern` per #1319.

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #1552: Update ut-stubs related to prototype/implementation scrub, #1474/#1551
**Is your feature request related to a problem? Please describe.**
Prototype/implementation discrepancies were resolved in #1551, but ut-stubs were not updated.

**Describe the solution you'd like**
Update ut-stubs

**Describe alternatives you've considered**
None

**Additional context**
#1474 and #1551

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Fix #1474 - This checks prototypes against implementation and fixes any differences (return type, parameter names, etc).  For the most part implementation was considered truth (fixed prototype) except for CFE_Status_t return type change.  Also fixes some but not all use of CFE_Status_t in the implementations.

Fix #1552 - note completed ut-stub updates after CCB, added in since they are trival.

Follow on work needed - Internal use of CFE_Status_t (#921)

**Testing performed**
Built and ran unit tests, all passed.  Built usersguide and confirmed no errors.

**Expected behavior changes**
None

**System(s) tested on**
 - Hardware: Docker on laptop
 - OS: Ubuntu 18.04
 - Versions: Bundle main + these commits

**Additional context**
Builds on commit from @zachar1a submitted in #1531, now closed as duplicate to this PR

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC
Zachary Gonzalez - Individual

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB:2021-05-19](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-May-19-2021) APPROVED
- Builds on community contribution
- Removes old UT_TimeHandler

**Comment by skliper** [comment]
Added in the ut-stub updates with 7e3effd

**Review by jphickey — APPROVED** [review]
Note, going forward we should consider the names in the header/documentation to be part of the API. That is, a name change in the header is treated similarly to an API change like adding or removing an argument.  That's because unit test hooks may now be referencing parameters by the names in the header/documentation.

So if/when in the future there are discrepancies found between header and implementation, it would be less impact (compatibility-wise) to update the implementation to match the header, rather than the header to match the implementation.

**Comment by astrogeco** [comment]
@skliper I see that the commits are all partials. Does their combination result in a full fix for both #1474 and #1552?

**Comment by zachar1a** [comment]
@astrogeco I only changed the implementation to match the prototypes for #1474. No work was done on my part to complete #921, another issue was also mentioned to remove the `extern` from both prototype and implementation. I didn't know if that should be another ticket or go in with this, so I just left them there.

**Comment by skliper** [comment]
@astrogeco Amended the commit message on the last one since it alone fixed #1552, the first two together fixed #1474.

**Pull request merged**
