### PR TITLE
Fix #1320 #1583 #508, Event ID updates

### LINKED ISSUE #508: Doxygen event documentation needs scrub
**Is your feature request related to a problem? Please describe.**
Doxygen event output doesn't match code in at least 1 case, see CFE_ES_INITSTATS_INF_EID

**Describe the solution you'd like**
Scrub event doxygen and confirm it matches actual output (and type)

**Describe alternatives you've considered**
Maybe #define the string as a single definition and link in documentation

**Additional context**
N/A

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #1320: `CFE_ES_MAX_EID` incorrect
**Is your feature request related to a problem? Please describe.**
Max EID incorrect:
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/inc/cfe_es_events.h#L46
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/inc/cfe_es_events.h#L1449

**Describe the solution you'd like**
Fix.

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #1583: Order event ID's and fix duplicates
**Is your feature request related to a problem? Please describe.**
The whole "MAX EID" concept for  avoiding conflicts is poorly followed, out of order EID's then lead to collisions.  Just one example shown here (there are multiple):
https://github.com/nasa/cFE/blob/176e3df03f54f7753cb34beb3e986202604d6cef/modules/sb/fsw/inc/cfe_sb_events.h#L195
https://github.com/nasa/cFE/blob/176e3df03f54f7753cb34beb3e986202604d6cef/modules/sb/fsw/inc/cfe_sb_events.h#L892

**Describe the solution you'd like**
Order EID's by number.  Put new ones at the end.  Remove the unused MAX EID value which is fragile anyways.

**Describe alternatives you've considered**
None

**Additional context**
#1320 - incorrect max

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Fix #1320 - Removed CFE_ES_MAX_EID and all the others (very fragile, especially when EIDs are out of order)
Fix #1583 - Ordered EID's and fixed duplicate assignments
Fix #508 -  Cleaned up EventID documentation
  - Removed format string and replaced with brief description
  - Reduce verbiage in full descriptions, made consistent and less "bi-directional" when there are multiple sources.  API/commands will reference EIDs.

**Testing performed**
Build an run unit tests, passed - TBD (not actually done yet)

**Expected behavior changes**
Deconflicted EIDs.

**System(s) tested on**
 - Hardware: Intel I5/Docker
 - OS: Ubuntu 18.04
 - Versions: Bundle main + this commit

**Additional context**
Did not address #1532, could be a big impact.
Wrote #1588 to track use of EID in multiple locations.

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by skliper** [comment]
Created draft and marked to review current approach.

**Comment by astrogeco** [comment]
[CCB:2021-06-02](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-02-2021) 
- Did this renumber Event IDs? Only 3 cases were changed.

**Comment by skliper** [comment]
Note a future improvement could be to change how commands are documented, use grouping instead of xrefitem (cross reference) to create the group and use a /brief to describe the command.  Then everywhere the command brief is useful could just `\copybrief #WHATEVER_CC`, would eliminate at least two copies of the brief command description for every event ID.  The current references/links help to prevent confusion, but the less opportunities for typos in repeated text the better.

**Comment by astrogeco** [comment]
Can I remove the WIP prefix?

**Comment by skliper** [comment]
> Can I remove the WIP prefix?

Done!

**Comment by astrogeco** [comment]
[CCB:2021-06-23](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-23-2021) APPROVED

**Pull request merged**
